export const upgrades = {
  "Armour Plating": {
    slots: 1,
    ammo: 0,
    specialRules: "+2 Hull",
    cost: 4,
    keywords: [],
    limit: null,
    allowedSponsors: [],
    ruleset: "BASE",
  },
  "Experimental Nuclear Engine": {
    slots: 0,
    ammo: 0,
    specialRules: "See rulebook",
    cost: 5,
    keywords: [],
    limit: 1,
    allowedSponsors: ["Mishkin"],
    ruleset: "BASE",
  },
  "Experimental Teleporter": {
    slots: 0,
    ammo: 0,
    specialRules: "See rulebook",
    cost: 7,
    keywords: [],
    limit: 1,
    allowedSponsors: ["Mishkin"],
    ruleset: "BASE",
  },
  "Extra Crewmember": {
    slots: 0,
    ammo: 0,
    specialRules: "+1 Crew, up to double starting crew",
    cost: 4,
    keywords: [],
    allowedSponsors: [],
    limit: null,
    ruleset: "BASE",
  },
  "Improvised Sludge Thrower": {
    slots: 1,
    ammo: 0,
    specialRules:
      "This vehicle may place the burst templates for its dropped weapons anywhere within a 360 arc of fire that is at least partially within medium range of this vehicle.",
    cost: 2,
    keywords: [],
    limit: 1,
    allowedSponsors: [],
    ruleset: "BASE",
  },
  "Nitro Booster": {
    slots: 0,
    ammo: 1,
    specialRules: "See rulebook",
    cost: 6,
    keywords: [],
    limit: null,
    allowedSponsors: [],
    ruleset: "BASE",
  },
  "Roll Cage": {
    slots: 1,
    ammo: 0,
    specialRules: "May ignore hits received from Flips.",
    cost: 4,
    keywords: [],
    limit: 1,
    allowedSponsors: [],
    ruleset: "BASE",
  },
  "Tank tracks": {
    slots: 1,
    ammo: 0,
    specialRules: "+1 Handling, -1 Max Gear, All terrain",
    cost: 4,
    keywords: ["All terrain"],
    limit: 1,
    allowedSponsors: [],
    ruleset: "BASE",
  },
  // sposor specific
  "Prison Vehicle": {
    slots: 0,
    ammo: 0,
    specialRules: "See rulebook",
    cost: -4,
    keywords: [],
    limit: 1,
    allowedSponsors: ["The Warden"],
    ruleset: "BASE",
  },
  "Louder Siren": {
    slots: 0,
    ammo: 0,
    specialRules:
      "Replace 'Bogey' with 'any enemy vehicle' for the purposes of the Siren special rules.",
    cost: 2,
    keywords: [],
    limit: 1,
    allowedSponsors: ["Highway Patrol"],
    ruleset: "BASE",
  },
  "MicroPlate Armour": {
    slots: 0,
    ammo: 0,
    specialRules: "+2 Hull",
    cost: 6,
    keywords: [],
    limit: null,
    allowedSponsors: ["Verney"],
    ruleset: "BASE",
  },
};
