export const vehicles = {
  Buggy: {
    weight: "Light",
    hull: 6,
    handling: 4,
    maxGear: 6,
    slots: 2,
    crew: 2,
    cost: 6,
    keywords: ["Roll cage"],
    ruleset: "BASE",
  },
  Car: {
    weight: "Middle",
    hull: 10,
    handling: 3,
    maxGear: 5,
    slots: 2,
    crew: 2,
    cost: 12,
    keywords: [],
    ruleset: "BASE",
  },
  "Performance Car": {
    weight: "Middle",
    hull: 8,
    handling: 4,
    maxGear: 6,
    slots: 2,
    crew: 1,
    cost: 15,
    keywords: ["Slip away"],
    ruleset: "BASE",
  },
  Truck: {
    weight: "Middle",
    hull: 12,
    handling: 2,
    maxGear: 4,
    slots: 3,
    crew: 3,
    cost: 15,
    keywords: [],
    ruleset: "BASE",
  },
  "Heavy Truck": {
    weight: "Heavy",
    hull: 14,
    handling: 2,
    maxGear: 3,
    slots: 5,
    crew: 4,
    cost: 25,
    keywords: [],
    ruleset: "BASE",
  },
  Bus: {
    weight: "Heavy",
    hull: 16,
    handling: 2,
    maxGear: 3,
    slots: 3,
    crew: 8,
    cost: 30,
    keywords: [],
    ruleset: "BASE",
  },

  "Drag Racer": {
    weight: "Light",
    hull: 4,
    handling: 4,
    maxGear: 6,
    slots: 2,
    crew: 1,
    cost: 5,
    keywords: ["Jet Engine"],
    ruleset: "BASE",
  },
  Bike: {
    weight: "Light",
    hull: 4,
    handling: 5,
    maxGear: 6,
    slots: 1,
    crew: 1,
    cost: 5,
    keywords: ["Full throttle", "Pivot"],
    ruleset: "BASE",
  },
  "Bike with Sidecar": {
    weight: "Light",
    hull: 4,
    handling: 5,
    maxGear: 6,
    slots: 2,
    crew: 2,
    cost: 8,
    keywords: ["Full throttle", "Pivot"],
    ruleset: "BASE",
  },
  "Ice Cream Truck": {
    weight: "Middle",
    hull: 10,
    handling: 2,
    maxGear: 4,
    slots: 2,
    crew: 2,
    cost: 8,
    keywords: ["Infuriating Jingle"],
    ruleset: "BASE",
  },
  Gyrocopter: {
    weight: "Middle",
    hull: 4,
    handling: 4,
    maxGear: 6,
    slots: 0,
    crew: 1,
    cost: 10,
    keywords: ["Airwolf", "Airborne", "Bombs away"],
    ruleset: "BASE",
  },
  Ambulance: {
    weight: "Middle",
    hull: 12,
    handling: 2,
    maxGear: 5,
    slots: 3,
    crew: 3,
    cost: 20,
    keywords: ["Uppers", "Downers"],
    ruleset: "BASE",
  },
  "Monster Truck": {
    weight: "Heavy",
    hull: 10,
    handling: 3,
    maxGear: 4,
    slots: 2,
    crew: 2,
    cost: 25,
    keywords: ["All terrain", "Up and Over"],
    ruleset: "BASE",
  },
  Helicopter: {
    weight: "Heavy",
    hull: 8,
    handling: 3,
    maxGear: 4,
    slots: 4,
    crew: 3,
    cost: 30,
    keywords: ["Airwolf", "Airborne", "Bombs away"],
    ruleset: "BASE",
  },
  Tank: {
    weight: "Heavy",
    hull: 20,
    handling: 4,
    maxGear: 3,
    slots: 4,
    crew: 3,
    cost: 40,
    keywords: ["All terrain", "Up and Over", "Pivot", "Turret"],
    ruleset: "BASE",
  },
  "War Rig": {
    weight: "Heavy",
    hull: 26,
    handling: 2,
    maxGear: 4,
    slots: 5,
    crew: 5,
    cost: 40,
    keywords: ["Articulated", "Ponderous", "Piledriver"],
    ruleset: "BASE",
  },
};
