export const handgun = {
  attackType: "Shooting",
  attack: "1D6",
  range: "Medium",
  slots: "-",
  ammo: "-",
  specialRules: "Blitz",
  crewFired: "Yes",
  cost: "-",
  allowedSponsors: [],
  ruleset: "BASE",
  limit: null,
};
export const weapons = {
  // always picked and available
  // basic weapons
  "Machine Gun": {
    attackType: "Shooting",
    attack: "2D6",
    range: "Double",
    slots: 1,
    ammo: 0,
    specialRules: "",
    crewFired: false,
    cost: 2,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Heavy Machine Gun": {
    attackType: "Shooting",
    attack: "3D6",
    range: "Double",
    slots: 1,
    ammo: 0,
    specialRules: "",
    crewFired: false,
    cost: 3,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Mini-Gun": {
    attackType: "Shooting",
    attack: "4D6",
    range: "Double",
    slots: 1,
    ammo: 0,
    specialRules: "",
    crewFired: false,
    cost: 5,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  // advanced
  "125mm Cannon": {
    attackType: "Shooting",
    attack: "8D6",
    range: "Double",
    slots: 3,
    ammo: 3,
    specialRules: "Blast, +2 hazard if not Tank",
    crewFired: false,
    cost: 6,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Arc Lightning Projector": {
    attackType: "Shooting",
    attack: "6D6",
    range: "Double",
    slots: 2,
    ammo: 1,
    specialRules: "Arc chain in short range",
    crewFired: false,
    cost: 6,
    allowedSponsors: ["Mishkin"],
    ruleset: "BASE",
    limit: null,
  },
  Bazooka: {
    attackType: "Shooting",
    attack: "3D6",
    range: "Double",
    slots: 2,
    ammo: 3,
    specialRules: "Blast",
    crewFired: false,
    cost: 4,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  BFG: {
    attackType: "Shooting",
    attack: "10D6",
    range: "Double",
    slots: 3,
    ammo: 1,
    specialRules: "Medium straight backwards, gear=1, haazards +3 ",
    crewFired: false,
    cost: 1,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Combat Laser": {
    attackType: "Shooting",
    attack: "3D6",
    range: "Double",
    slots: 1,
    ammo: 0,
    specialRules: "Splash",
    crewFired: false,
    cost: 5,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Death Ray": {
    attackType: "Shooting",
    attack: "3D6",
    range: "Double",
    slots: 1,
    ammo: 1,
    specialRules: "5+ un-cancelled hits removes target from play",
    crewFired: false,
    cost: 3,
    allowedSponsors: ["Mishkin"],
    ruleset: "BASE",
    limit: null,
  },
  Flamethrower: {
    attackType: "Shooting",
    attack: "6D6",
    range: "Large Burst",
    slots: 2,
    ammo: 3,
    specialRules: "Splash, Fire. Indirect",
    crewFired: false,
    cost: 4,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Grabber Arm": {
    attackType: "Shooting",
    attack: "3D6",
    range: "Short",
    slots: 1,
    ammo: 0,
    specialRules: "Toss",
    crewFired: false,
    cost: 6,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Grav Gun": {
    attackType: "Shooting",
    attack: "3D6*",
    range: "Double",
    slots: 1,
    ammo: 1,
    specialRules: "Electrical. Gravity Manipulation",
    crewFired: false,
    cost: 2,
    allowedSponsors: ["Mishkin"],
    ruleset: "BASE",
    limit: null,
  },
  Harpoon: {
    attackType: "Shooting",
    attack: "5D6*",
    range: "Double",
    slots: 1,
    ammo: 0,
    specialRules: "Harpoon",
    crewFired: false,
    cost: 2,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Kinetic Super Booster": {
    attackType: "Shooting",
    attack: "(6D6)",
    range: "Double",
    slots: 2,
    ammo: 1,
    specialRules: "Gear +1 instead of damage",
    crewFired: false,
    cost: 6,
    allowedSponsors: ["Mishkin"],
    ruleset: "BASE",
    limit: null,
  },
  "Magnetic Jammer": {
    attackType: "Shooting",
    attack: "-",
    range: "Double",
    slots: 0,
    ammo: 0,
    specialRules: "Target can't use ammo next activation",
    crewFired: false,
    cost: 2,
    allowedSponsors: ["Mishkin"],
    ruleset: "BASE",
    limit: null,
  },
  Mortar: {
    attackType: "Shooting",
    attack: "4D6",
    range: "Double",
    slots: 1,
    ammo: 3,
    specialRules: "Indirect",
    crewFired: false,
    cost: 4,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  Rockets: {
    attackType: "Shooting",
    attack: "6D6",
    range: "Double",
    slots: 2,
    ammo: 3,
    specialRules: "",
    crewFired: false,
    cost: 5,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  Thumper: {
    attackType: "Shooting",
    attack: "-",
    range: "Medium",
    slots: 2,
    ammo: 1,
    specialRules: "Indirect. Targets make gear+2 (max 6) flip check",
    crewFired: false,
    cost: 4,
    allowedSponsors: ["Mishkin"],
    ruleset: "BASE",
    limit: null,
  },
  "Wall Of Amplifiers": {
    attackType: "Shooting",
    attack: "-",
    range: "Medium",
    slots: 3,
    ammo: 0,
    specialRules: "*See rules",
    crewFired: false,
    cost: 4,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Wreck Lobber": {
    attackType: "Shooting",
    attack: "-",
    range: "Double/Dropped",
    slots: 4,
    ammo: 3,
    specialRules: "*See rules, Low-loader, Dumper",
    crewFired: false,
    cost: 4,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Wrecking Ball": {
    attackType: "Shooting",
    attack: "*",
    range: "Short",
    slots: 3,
    ammo: 0,
    specialRules: "Steel Ball",
    crewFired: false,
    cost: 2,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  // crew fired
  Blunderbuss: {
    attackType: "Shooting",
    attack: "2D6",
    range: "Small Burst",
    slots: 0,
    ammo: 0,
    specialRules: "Splash",
    crewFired: true,
    cost: 2,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Gas Grenades": {
    attackType: "Shooting",
    attack: "(1D6)",
    range: "Medium",
    slots: 0,
    ammo: 5,
    specialRules: "Blitz, Choking Gas, Indirect",
    crewFired: true,
    cost: 1,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  Grenades: {
    attackType: "Shooting",
    attack: "1D6",
    range: "Medium",
    slots: 0,
    ammo: 5,
    specialRules: "Blast, Indirect, Blitz",
    crewFired: true,
    cost: 1,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  Magnum: {
    attackType: "Shooting",
    attack: "1D6",
    range: "Double",
    slots: 0,
    ammo: 0,
    specialRules: "Blast",
    crewFired: true,
    cost: 3,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Molotov Cocktails": {
    attackType: "Shooting",
    attack: "1D6",
    range: "Medium",
    slots: 0,
    ammo: 5,
    specialRules: "Fire, Indirect, Blitz",
    crewFired: true,
    cost: 1,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  Shotgun: {
    attackType: "Shooting",
    attack: "3/2/1D6",
    range: "Short/Medium/Long",
    slots: 0,
    ammo: 0,
    specialRules: "",
    crewFired: true,
    cost: 4,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Steel Nets": {
    attackType: "Shooting",
    attack: "(3D6)",
    range: "Short",
    slots: 0,
    ammo: 0,
    specialRules: "Blast",
    crewFired: true,
    cost: 2,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Submachine Gun": {
    attackType: "Shooting",
    attack: "3D6",
    range: "Medium",
    slots: 0,
    ammo: 0,
    specialRules: "",
    crewFired: true,
    cost: 5,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  // Dropped
  "Caltrop Dropper": {
    attackType: "Dropped",
    attack: "2D6",
    range: "Small Burst",
    slots: 1,
    ammo: 3,
    specialRules: "Treacherous, remains until damage is caused",
    crewFired: false,
    cost: 1,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Glue Dropper": {
    attackType: "Dropped",
    attack: "-",
    range: "Large Burst",
    slots: 1,
    ammo: 1,
    specialRules: "Treacherous, gear -2",
    crewFired: false,
    cost: 1,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Mine Dropper": {
    attackType: "Dropped",
    attack: "4D6",
    range: "Small Burst",
    slots: 1,
    ammo: 3,
    specialRules: "Blast",
    crewFired: false,
    cost: 1,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Napalm Dropper": {
    attackType: "Dropped",
    attack: "4D6",
    range: "Small Burst",
    slots: 1,
    ammo: 3,
    specialRules: "Fire",
    crewFired: false,
    cost: 1,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Oil Slick Dropper": {
    attackType: "Dropped",
    attack: "-",
    range: "Large Burst",
    slots: 0,
    ammo: 3,
    specialRules: "Treacherous",
    crewFired: false,
    cost: 2,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "RC Car Bombs": {
    attackType: "Dropped",
    attack: "4D6",
    range: "Short",
    slots: 0,
    ammo: 3,
    specialRules: "Remote-Controlled Car",
    crewFired: false,
    cost: 3,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Sentry Gun": {
    attackType: "Dropped",
    attack: "2D6",
    range: "Short/Medium",
    slots: 0,
    ammo: 3,
    specialRules: "Sentry Gun",
    crewFired: false,
    cost: 3,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Smoke Dropper": {
    attackType: "Dropped",
    attack: "-",
    range: "Large Burst",
    slots: 0,
    ammo: 3,
    specialRules: "Provides cover",
    crewFired: false,
    cost: 1,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  // Smash Weapons
  Ram: {
    attackType: "Smash",
    attack: "+2D6",
    range: "Smash",
    slots: 1,
    ammo: 0,
    specialRules: "No hazards gained during collisions on declared facing",
    crewFired: false,
    cost: 4,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: null,
  },
  "Exploding Ram": {
    attackType: "Smash",
    attack: "+6D6",
    range: "Smash",
    slots: 0,
    ammo: 1,
    specialRules: "Highly Explosive. Limit of 1",
    crewFired: false,
    cost: 3,
    allowedSponsors: [],
    ruleset: "BASE",
    limit: 1,
  },
};
